include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    - avoid_relative_lib_imports
    - always_use_package_imports
    - cancel_subscriptions
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_redundant_argument_values
    - prefer_final_locals

analyzer:
  errors:
    avoid_relative_lib_imports: error
    always_use_package_imports: error
    cancel_subscriptions: error
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    avoid_redundant_argument_values: error
    prefer_final_locals: error
    deprecated_member_use: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  language:
    strict-casts: true
    strict-raw-types: true

  plugins:
    - custom_lint
